# Generated by Django 4.1.7 on 2023-02-17 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('tipo', models.CharField(max_length=255)),
                ('region', models.CharField(max_length=255)),
                ('topologia', models.CharField(max_length=255)),
                ('titular', models.CharField(max_length=255)),
                ('inversion', models.DecimalField(decimal_places=4, max_digits=10)),
                ('fecha_presentacion_ingreso', models.CharField(max_length=255)),
                ('estado', models.CharField(max_length=255)),
                ('mapa', models.CharField(max_length=255)),
            ],
        ),
    ]
