# Generated by Django 4.1.7 on 2023-02-17 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BikeStation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=200)),
                ('empty_slots', models.IntegerField()),
                ('free_bikes', models.IntegerField()),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('timestamp', models.DateTimeField()),
                ('address', models.CharField(max_length=200)),
                ('altitude', models.FloatField()),
                ('ebikes', models.IntegerField()),
                ('has_ebikes', models.BooleanField()),
                ('last_updated', models.IntegerField()),
                ('normal_bikes', models.IntegerField()),
                ('payment', models.JSONField()),
                ('payment_terminal', models.BooleanField()),
                ('post_code', models.CharField(max_length=10)),
                ('renting', models.IntegerField()),
                ('returning', models.IntegerField()),
                ('slots', models.IntegerField()),
                ('uid', models.CharField(max_length=200)),
            ],
        ),
    ]
